### ISSUE TITLE
Feature: User can view all entries in the Compendium

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/hyrule-compendium#1]
## ⚙️ Feature

> ##### Once merged, user can browse the entire contents of the Hyrule Compendium on both desktop and mobile views.

## 📐 Functionality

> ##### User can load the web application and be presented with a display of all the Entries. User can use the navigation icons to switch between categories. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-08-01 at 10 43 26 AM](https://user-images.githubusercontent.com/49361894/182209994-c497270b-cb76-4e78-ad80-b27d04217b45.png)
![Screen Shot 2022-08-01 at 10 43 51 AM](https://user-images.githubusercontent.com/49361894/182210008-99a666cf-4c0b-4726-b89d-8c3af7caf3a1.png)
![Screen Shot 2022-08-01 at 10 44 09 AM](https://user-images.githubusercontent.com/49361894/182210019-c5fbfd86-dfc0-47e1-a384-ca436c62cfe0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Begin the initial implementation of the row and column layout classes that will need to adapt to changing view sizes.
- [x] Utilize hard coded data to create mock entries that implement the design from the wireframe. This will be done for the images, name, and compendium entry number
- [x] Implement the navigation bar at the top of the page without navigation functionality
- [x] Implement the navigation icons but without view swapping functionality
- [x] Implement functionality for requesting data from the server and store the response in the data model.
- [x] Implement functionality for rendering the entries based on our mock entries
- [x] Implement view swapping functionality between the different navigation icon views
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
