### ISSUE TITLE
Feature: User can see detailed entry view

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/hyrule-compendium#2]
## ⚙️ Feature

>When clicking on an entry in the Compendium, the user is greeted with a detailed view of the entry.

## 📐 Functionality

> While browsing the Compendium, the user can click on a specific entry to view the detailed view of the entry. This will include a summary of the entry, the location on the map, and any characteristics as it pertains to the item.  

## 🖼️ Wireframes

> 
![Screen Shot 2022-08-01 at 11 00 28 AM](https://user-images.githubusercontent.com/49361894/182212590-5ccca4bf-769e-4a1d-bf4d-97e158394a76.png)
![Screen Shot 2022-08-01 at 11 00 57 AM](https://user-images.githubusercontent.com/49361894/182212608-6f4efb87-0b33-4b2f-946e-acfbd45d3580.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Fix header and navigation icons to remain visible through scroll
- [x] Implement CSS for highlighting an entry with mouseover event
- [x] Create mock entry detail modal for Compendium item.  Ensure this mock entry meets desktop and mobile design spec
- [x] Implement dom functionality for rendering this modal
- [x] Implement click handler functionality for clicking on modal entry and rendering modal on screen
- [x] Ensure that modal design meets Figma spec
- [x] Remove any commented code, console log statements, and unnecessary styling.
- [x] Create gif of feature
