### ISSUE TITLE
Feature: User can sort entries

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/hyrule-compendium#3]
## ⚙️ Feature

> ##### When merged, user may sort entries by either its name or its compendium item number.

## User can sort entries. Sorting is done numerically or alphabetically. 

> ##### User can click the sort icon on the navigation menu to render the sort drop down. There, the user can either sort the entries alphabetically or by number. By default, the entries are sorted numerically. 

## 🖼️ Wireframes

> 
![Screen Shot 2022-08-01 at 11 04 18 AM](https://user-images.githubusercontent.com/49361894/182213243-4d0b14e9-baaf-4a42-a656-1c837fc56313.png)
![Screen Shot 2022-08-01 at 11 04 34 AM](https://user-images.githubusercontent.com/49361894/182213263-09c58066-d42b-41b1-8338-92ea699ba4dc.png)
![Screen Shot 2022-08-01 at 11 04 50 AM](https://user-images.githubusercontent.com/49361894/182213294-b4fce92c-f849-4a15-98b7-10e47135f42f.png)
![Screen Shot 2022-08-01 at 11 05 09 AM](https://user-images.githubusercontent.com/49361894/182213315-2c7ca1b6-3de6-474c-96e5-7847cd2a2477.png)
![Screen Shot 2022-08-01 at 11 05 21 AM](https://user-images.githubusercontent.com/49361894/182213347-ed51bee7-16f6-4d66-8262-6ce61f466386.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update sort icon to a font awesome icon rather than png icon.
- [x] Implement mock sort entries dropdown screen
- [x] Implement event listener on filter button to display this drown down screen
- [x] Implement functionality for rendering list of entries by specified sort once the user changes the sort selection. This will happen behind the overlay. 
- [x] Ensure proper functionality on both mobile and desktop
- [x] Remove any unnecessary comments, log methods, and necessary CSS
- [x] Create a gif displaying the feature in action
