### ISSUE TITLE
Feature: User can search entries

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/hyrule-compendium#4]
## ⚙️ Feature

> ##### When merged, users can search all entries in the Compendium. 

## 📐 Functionality

> ##### Users can click on the search icon in the navigation menu to be greeted with a search box. From there, the user can search for a specific item in the Compendium. 

## 🖼️ Wireframes

> 
![Screen Shot 2022-08-01 at 11 09 02 AM](https://user-images.githubusercontent.com/49361894/182213861-73a4cb3c-7cae-48b5-bb01-5f2cc693f675.png)
![Screen Shot 2022-08-01 at 11 09 11 AM](https://user-images.githubusercontent.com/49361894/182213902-6c7c0de9-0546-4220-9323-9e378365fe5a.png)
![Screen Shot 2022-08-01 at 11 09 22 AM](https://user-images.githubusercontent.com/49361894/182213917-d470caee-7c72-40dd-9324-5d2fbed6ce09.png)
![Screen Shot 2022-08-01 at 11 09 32 AM](https://user-images.githubusercontent.com/49361894/182213926-ecd75e94-911d-42bc-859d-02588a95a406.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Implement search bar that will be placed over header nav bar into HTML.
- [x] Add an event listener to the search icon that will display  this search bar. 
- [x] Add an event listener to the x icon that will close the search bar
- [x] Implement functionality that will render matching entries when user types each character 
- [x] Ensure that functionality works on both mobile and desktop
- [x] Remove any console log methods and unnecessary code
- [x] Remove unnecessary styling
- [x] Create a gif demonstrating the feature.
