### ISSUE TITLE
Feature: User can browse favorites in the Compendium

### ISSUE THREAD

**Issue by arjunkahlon** [arjunkahlon/hyrule-compendium#5]
## ⚙️ Feature

> ##### User will be able to favorite items in the Compendium. The favorites will be accessible from the favorites icon in the navigation menu.

## 📐 Functionality

> ##### Every detailed entry view will contain an unselected heart icon. The user will be able to click the heart to add the entry to the favorites list. This favorites list is accessible from the heart icon in the navigation menu. In the favorites list, the user will be able to remove any favorited item from the favorites list. This list will save when exiting and relaunching the application. 

## 🖼️ Wireframes

> 
![Screen Shot 2022-08-01 at 11 11 41 AM](https://user-images.githubusercontent.com/49361894/182214963-0a9d5670-7d88-4a38-bcab-e8e13095b05d.png)
![Screen Shot 2022-08-01 at 11 11 57 AM](https://user-images.githubusercontent.com/49361894/182215025-bdec86f2-531b-44dd-96e8-30df216e09cd.png)
![Screen Shot 2022-08-01 at 11 12 10 AM](https://user-images.githubusercontent.com/49361894/182215039-f69f0df2-82b0-4f0c-b403-03b482d4db57.png)
![Screen Shot 2022-08-01 at 11 12 24 AM](https://user-images.githubusercontent.com/49361894/182215051-0d10a183-e7eb-4bc0-92de-202c40ce54c9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a mock favroite sidebar modal that takes up the entire screen on mobile
- [x] Add mock favorites entries to implement design
- [x] Add event listener to favorites icon that displays this favorite view
- [x] Implement functionality for adding Compendium entries to favorites. This will be done through the detail view of an item
- [x] Ensure that favorited items display a red heart when view their detail view screen
- [x] Implement functionality for removing entries from user favorites
- [x] Implement the dom functionality that will allow a user to remove a favorited item from the favorites view. The favorites screen should repopulate after an item is removed.
- [x] Implement the functionality for removing from the favorites array when clicking the red heart on the entry detail view
- [x] Implement local storage functionality for retrieving user local favorites on load.
- [x] Test functionality on mobile and desktop
- [x] Remove any console log methods and/or unnecessary code and CSS style selectors
- [x] Create a gif demonstrating the feature.
